### ISSUE TITLE
Multiple threads spawned

### ISSUE THREAD

**Issue by Eric-CH-Chen** [evolbioinfo/pastml#10]
Dear developer,

When I run PastML on command line mode, multiple threads gets spawned. Is there a way to limit the number of threads? Or better yet, control how many CPUs gets assigned to it? 

Thank you very much.

OS: RH 7.2
Version 1.9.20

**Comment by annazhukova** [comment]
Dear Eric,

I am sorry for taking so long to address your issue (I have somehow overseen it before), and thank you for pointing out the thread problem!

I have added the --threads option in pastml version 1.9.25, which should allow you to control the number of CPUs (optimal is the number of characters (columns) for which ARC is performed + 1).

Thank you,
Anna
