### ISSUE TITLE
'list' object has no attribute 'read'

### ISSUE THREAD

**Issue by Morteza-M-Saber** [evolbioinfo/pastml#14]
Im trying to run Pastml on a computer cluster, the output is produced and seems to be okay but there is the following error on the screen:

`pastml:ERROR:23:12:51 Did not manage to save the annotated tree in nexus format due to the following error: 'list' object has no attribute 'read'`

Is it a real issue or is just a warning that could be ignored?
Thanks,

**Comment by annazhukova** [comment]
Hi and thanks for trying PastML!

This a warning that can be safely ignored. It does not affect the other results and only means that the conversion of the tree with named internal nodes from newick (produced among the output files) to nexus did not work. But if you ever need nexus you can convert for example with [gotree](https://github.com/evolbioinfo/gotree).

I will look at this soon though and fix the nexus output in the future versions of PastML.

Cheers,
Anna

**Comment by george-githinji** [comment]
I am encountering this same error. Since i am using a snakemake pipeline, it terminates without writing results to file.
