### ISSUE TITLE
not able to run Albanian example data

### ISSUE THREAD

**Issue by TYMichaelsen** [evolbioinfo/pastml#15]
Hi,

I tried to download the Albanian testset (`Albanian.tree.152tax.tre` and `data.txt`) and run pastml from within the same directory, first through singularity:

`singularity run docker://evolbioinfo/pastml --tree Albanian.tree.152tax.tre --data data.txt --columns Country --data_sep ,`

And through a conda env, made according to guidelines:

`pastml --tree Albanian.tree.152tax.tre --data data.txt --columns Country --data_sep ,`

I consistently get the error: `pastml:ERROR Did not manage to save the annotated tree in nexus format due to the following error: 'list' object has no attribute 'read'`

I also tried the version of the Albanian dataset downloadable from here: https://pastml.pasteur.fr/. I cannot figure out what I'm doing wrong, any help will be much appreciated! 
Thanks,
Thomas

**Comment by annazhukova** [comment]
Hi Thomas,

Thanks for trying PastML and for reporting this issue. I will look at this soon and fix the nexus output in the future versions of PastML.

But in the meanwhile you can safely use PastML as is, just ignoring this error message: It does not affect the other results and only means that the conversion of the tree with named internal nodes from newick (produced among the output files) to nexus did not work. If you ever need nexus you can convert for example with [gotree](https://github.com/evolbioinfo/gotree).

Sorry about it.

Cheers,
Anna

**Comment by annazhukova** [comment]
Sorry for such a long delay. The issue should be solver in v1.9.34
