### ISSUE TITLE
put pastml on conda-forge?

### ISSUE THREAD

**Issue by harmsm** [evolbioinfo/pastml#17]
Pastml is great. Would it be possible to place it on conda-forge to allow conda installation of pastml? This would increase ease-of-access for users. I am happy to set up the conda-forge submission if helpful and okay with you. 

**Is your feature request related to a problem? Please describe.**
We're using pastml as part of a [pipeline](https://topiary-asr.readthedocs.io/en/latest/index.html) to streamline ancestral protein sequence reconstruction. We're using pastml for gap character reconstructions. In the medium term, we plan to use it as an option for visualization. We want to give our users the ability to install our pipeline from a package manager. Unfortunately, some of the other software in the pipeline are only available on conda and would be very difficult to port to pip. This makes conda the best option as the package manager. conda recipes do not allow pip dependencies, so pastml is blocking our ability do a conda install.

**Describe the solution you'd like**
Place pastml on conda-forge. 

**Describe alternatives you've considered**

1. Drop pastml from our pipeline.
2. Figure out how to port several other complex software packages to pip. 
3. Make it so users have to install our pipeline from source. 

**Additional context**
I would be happy to take point on the conda-forge submission. (If you're not familiar with the process, it's fairly straightforward. It involves constructing a meta.yml file and submitting it as a PR on a conda-forge repo. https://conda-forge.org/#add_recipe).

**Comment by harmsm** [comment]
I just submitted a PR with a draft conda recipe if it helps move this along. Thanks!

**Comment by annazhukova** [comment]
Dear @harmsm ,

Thank you very much for the request and for your help with the conda recipe! I am currently in the process of uploading PastML to bioconda (as it has bioconda dependencies), would that be fine? I am waiting for my bioconda [pull request](https://github.com/bioconda/bioconda-recipes/pull/36489) to be approved.

Sorry for the delays.

**Comment by harmsm** [comment]
Bioconda is great! Thanks so much for working on it and for the great package. 

Mike

**Comment by annazhukova** [comment]
Pastml shoud be available on bioconda by now (for python >= 3.8).

**Comment by harmsm** [comment]
Excellent!  Just installed via conda. Thanks so much!
