### ISSUE TITLE
Does it only support discrete data predictions?

### ISSUE THREAD

**Issue by zpinocchio** [evolbioinfo/pastml#20]
I want to reconstruct the number of ancestral genetic families, got some errors.

raise ValueError('Character "{}" has {} unique states annotated in this tree: {}, '
ValueError: Character "gene_count" has 62 unique states annotated in this tree: {'5591', '2965', '424', '9785', '7651', '7093', '2715', '5545', '6306', '9886', '6523', '2827', '2602', '7085', '7529', '7871', '9127', '8464', '3831', '2440', '9790', '8655', '7018', '6024', '3211', '6283', '4056', '5680', '9132', '9105', '7766', '1115', '1099', '9608', '9203', '1932', '7996', '3468', '4013', '1257', '8485', '5147', '7666', '7589', '7890', '4710', '1357', '1271', '1722', '5056', '975', '2984', '8393', '4228', '8917', '6265', '8136', '8646', '4119', '5371', '4641', '8419'}, which is too much to infer on a tree with only 62 tips. Make sure the character you are analysing is discreet, and if yes use a larger tree.

**Comment by annazhukova** [comment]
Dear zpinocchio,

PastML only implements models (F81, JC) for characters with discrete independent states (e.g. countries). Unfortunately, these models are not suitable for your analysis. You could probably find some appropriate models in BEAST instead.

**Comment by annazhukova** [comment]
Dear zpinocchio,

The character state evolution models available in PastML (F81, JC) are only suitable for characters with discrete unordered states (e.g. countries), where the numkber of states is limited and significantly smaller than the number of tree tips. All this is not the case for your analysis. You could probably find some more appropriate models in BEAST instead.
